### ISSUE TITLE
[BUG] 'Open new tab' button problems

### ISSUE THREAD

**Issue by letmeknov** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#112] opened 2021-03-07 15:12 UTC
**Describe the bug**
'Open new tab' button which has to be on the right side of last opened tab has two problems, sometimes it doesn't show at all, sometimes it is visible but doesn't do any thing when you click on it. Problem might be related to extension called 'Simple Tab Groups', because it only happens when I use this extension and your tool, so some groups (with tabs) got those problems, some don't. 

**To Reproduce**
Steps to reproduce the behavior, or a brief explanation on it:
1. Install [Simple Tab Groups](https://github.com/drive4ik/simple-tab-groups) Firefox extension.
2. Apply Quantum Nox Patcher 1.7.12 (enabling only Multi-row Tabs 3 rows and leave everything else unchecked)
3. Create 3-5 groups with random tabs, play around switching groups, restart Firefox and look for a group which has the bugged 'Open new tab' button.

**Screenshots**
The button is merged with tab and doesn't work:
![Screenshot from 2021-03-07 15-36-122](https://user-images.githubusercontent.com/52158526/110244511-ee7cbf80-7f56-11eb-8c6d-56c21820b213.jpg)
No button at all:
![Screenshot from 2021-03-07 15-36-1222](https://user-images.githubusercontent.com/52158526/110244513-efadec80-7f56-11eb-8501-2480a50d3202.jpg)

**Desktop (please complete the following information):**
 - OS: Fedora 33 (Workstation Edition) x64
 - Version 33
 - Browser: Firefox 86.0

**Comment by Izheil** [comment] 2021-03-07 22:41
It seems to be a regresion caused by the last fix of multirow.
Adding a more specific selector fixes the issue, so I pushed to the multirow files.
Should be fixed on [the lastest release](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases)!

**Closed** 2021-03-14 20:11 UTC
Labels: Bug, Multirow
