### ISSUE TITLE
Linux Debian ESR 60.5

### ISSUE THREAD

**Issue by DebSec** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#40] opened 2019-02-07 05:01 UTC
When replying to emails or composing in Protonmail online I get a all dark input area. This also happens on eBay in advanced editing in the description area. When I remove the code
/* COMMENT OUT THIS SECTION IF BROWSING LOCAL HTML PAGES */ in userContent.css 
I can use the pages correctly. It then will affect a good amount of colorings elsewhere.

https://imgur.com/a/ntDLVdt

I also have issues with some add-on areas not showing text correctly. (Canvasblocker and others) This I can't track down to fix.

**Comment by DebSec** [comment] 2019-02-07 07:56
I had removed the correct portion of the code I was referring about previously. I added your edits. Protonmail is working now. eBay is not.
https://imgur.com/a/tn8mAdB
If I click on the HTML tab and go back to the Standard tab the dark color turns to white on eBay. I did not find the selector offhand.

With the element picker for uBlock the white background is fine but the text is to light colored and needs to be darker. It is a poor image the second one but I think you will understand.

**Comment by DebSec** [comment] 2019-02-07 18:10
I had some luck. The eBay listing page is working correctly and also Protonmail for the dark input background going back to white. I now have some issues in eBay with there wishlist section and checkboxes not displaying correctly (I had to use different code for checkbox and radio for it to work on linux). I can live with the weird anomaly going on there for now.

I'm still having issues with the addon preferences page with it being dark with dark text. I enabled the section in userChrome that you suggested and had no luck as the colors were still dark for a background when going to the preferences pages.

I also edited out the uBlock code under
/* Ublock Origin element picker window */
&
/* Fix for Ublock Origin Element picker and DOM inspector (while keeping about:blank dark) */
&
/* Fix for Ebay page when not using userstyles */

Now the element picker has dark background on upper box with dark text and the bottom is now displaying correctly.

https://imgur.com/a/jazaeMU

Thanks and have a good day.

**Comment by Izheil** [comment] 2019-02-07 19:11
Checkboxes colors depend on your OS, and they vary greatly. If you want your default OS checkboxes don't use checkboxes.as.css at all.

As for the wishlist section, I can't seem to find it on ebay, but the only issue that could be causing it from the theme is the about:blank section, which you already deleted, did you try without the theme?

Ublock element picker is showing completelly white for me without the code from userchrome, even when having the <code>about:blank</code> rule enabled (but you have it disabled, so that shouldn't be the problem anyway). Either you are using some other custom code, or your OS theme is turning it black. 

Worst case scenario, you can turn it white again enabling the rule for the selector <code>#ublock0-epicker section > div:first-child > textarea </code>inside the <code>/* Ublock Origin element picker window */</code> section and choosing a #fff background and #000 color (for black text).

As for the addon preferences, if you mean the ones inside <code>about:addons</code>, those depend on the extensions, (so they are like an iframe that comes from the extension you install), so I can't change the text color for them. You can although add this rule inside the <code>about:addons</code> section:

<code>#addon-options {background-color: #fff !important}</code>

...Which will turn the settings section for addons white for better readibility.

**Comment by DebSec** [comment] 2019-02-07 20:04
I'm in OK shape now. The code for about:addons worked good 
(#addon-options {background-color: #fff !important}).
Now the areas needed are usable and still have the theme around the pertinent areas intact.

Adding the uBlock color changes worked good enough now so that it is usable.

Thanks for that.
____________________________
We have conversed in the past in another post about the checkboxes and radio buttons. I can't find any setting in Debian Cinnamon with the system settings to change the checkboxes in the themes. I have to add custom code for the userContent so that the "Update addons automatically checkbox shows correctly. I also have to use different code for the main elements in the menu bar for the checkboxes and the radio.

The issue with eBay is they have new code and old code for the wishlists. First you navigate to an item and add it to your wishlist or lists. Then when browsing the wishlist area you can view and select a checkbox to delete it from the wishlist. The old code that you can access works correctly. In other areas there code is still old like previous bids and such and display there properly. This is not something I need to be addressing as of today. I was mentioning it.

_____________________________________________________
We have talked about the tooltips on the about:addons page. That area we figured might also be affected by the O/S and theme or settings.
There I get dark text on the dark background.
_____________________________________________________________________
I have altered code for the about:config pages and the bookmarks menu to display the code correctly for Linux.

____________________________________________________________________


Other than those annoyances the theme woks relatively well with all my changes.
If I find the time I will perhaps create a repository with the Linux edits for reference.

You can close this unless you have more code for me. Thanks

**Comment by DebSec** [comment] 2019-02-07 21:33
I was browsing about:about and checking various links and did come across different checkbox issues on some pages. Some looked to be fine and some were not. The ones that had issues looked the same on eBay. You could use them but they would not change in anyway to let you know they were checked. I can get by as your code did not work for me but the code I use works for the most part.

`menuitem[type="checkbox"], menuitem[type="radio"] {
  -moz-appearance: none!important;
  box-shadow: none!important; 
  color: #000 !important;
  filter: invert(81%)}

/* ::::: checkmark image ::::: */

.checkbox-check {
  -moz-appearance: checkbox;
  margin: 2px;
}

checkbox:not([disabled="true"]):hover {
  color: transparent;
  text-shadow: none;
}`

https://imgur.com/a/VJU0XJc

**Comment by Izheil** [comment] 2019-02-07 23:44
Ah yes, the ESR specific checkboxes, I had forgotten about that. Yes, those seem to appear correctly on the stable version (which is the main aim of this theme). Since you got it working, I guess there is not much to add, since adding the fix for ESR for those checkboxes seem to cause other issues on the stable version.

At least, It didn't seem to happen on the linux distributions I tested, so I'm not sure if it's specifically some distribution, but it seems to be more of an issue of the ESR versions.

The tooltips seem alright even on the about:addons on stable firefox, but I guess you could try with <code>tooltip * {color: ddd !important}</code> inside the tooltips file you are using. More than that, unless the tooltips got changed by the custom checkbox inversion rules (doubtful, but... could happen?), you can always try to give tooltips a more neutral background color like #666 or #777, but again, I'm not sure what could be causing that, since on stable I can't reproduce the issue, so I can't help much there.

Anyway, if everything is working (for the most part at least), I guess I can't add more than what you already have, so I'll close the issue.

**Closed** 2019-02-07 23:45 UTC

**Comment by DebSec** [comment] 2019-02-08 02:05
I did find a fix for the tooltips to work throughout the browser. In time I think Mozilla is phasing out the end users JavaScript. .

You obviously know where this goes and what it does.

UserChrome.js or tooltips.uc.js

XPCOMUtils.defineLazyGetter(FullScreen, "useLionFullScreen", function() {
    return false;
});
// ==UserScript==
// @name           TOOLTIPS
// @namespace      TOOLTIPS added through javascript
// @version        0.1
// @note           DebSec
// ==/UserScript==
(function() {
    var css =`
/* TOOLTIPS */
tooltip, .statuspanel-label {
  -moz-appearance: none !important;
  background-color: rgba(20,20,20,0.8) !important;
  opacity: 0.8 !important; 
  color: #eee !important;
  border: 1px solid #333 !important;
  padding: 5px !important;
}`;

    var sss = Cc['@mozilla.org/content/style-sheet-service;1'].getService(Ci.nsIStyleSheetService);
    var uri = makeURI('data:text/css;charset=UTF=8,' + encodeURIComponent(css));
    sss.loadAndRegisterSheet(uri, sss.AGENT_SHEET);
})();

**Comment by Izheil** [comment] 2019-02-08 02:29
That's odd, any of the tooltips*.as.css should already have AGENT_SHEET level to override any other setting from firefox if you are applying the userchrome.xml method, it didn't work without injecting it with a JS file?

**Comment by DebSec** [comment] 2019-02-08 03:17
Yes @Izheil ,
This is loaded as a external JavaScript file. In your userChrome you call it or load it with:
/*toolbarbutton#alltabs-button {  
    -moz-binding: url("userChrome.xml#js");
}

In which it would be  userChrome.js
You could also create a .uc.js file and load it from there e.g. tooltips.uc.js

I load my files .xml and .js differently using base64 code, Some of the code I did provide in the JS is redundant with the agent.

I had at one time gave you my chrome folder. You could browse that if you still have it.

Anyway it works great for now.
