### ISSUE TITLE
Menus Now Scroll Too

### ISSUE THREAD

**Issue by Captaindl** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#51] opened 2020-03-10 10:35 UTC
I've been using Quantum Nox for a while now and (although sometimes it needs some tweaking after Firefox updates) it has always worked.  After Firefox was updated to 73.0.1 all my menus seem to be trying to fit into three lines with a scrollbar too.  Is this something I've done wrong or a bug?

![scrollingMenu](https://user-images.githubusercontent.com/62013247/76304110-b77bbb80-62ba-11ea-84ab-3e3112b20b08.png)

**Comment by majoraswrath360** [comment] 2020-03-10 11:04
No issues here so this must be on your end. Probably because of other modifications you did. Try a clean firefox install.

**Comment by Izheil** [comment] 2020-03-10 18:21
I can't seem to reproduce the issue either. As majoraswrath360 said, try a clean install, and only apply the unchanged userchrome file to see if the issue persists.
Judging by the scrollbar you must be using Windows, so it doesn't seem to be a specific OS issue either.

**Comment by DasRentier** [comment] 2020-03-12 21:09
For five days I can only see a small window where there should be some rows in the app multi-account containers . When I disable my userChrome.css it's working again.
![multi-account containers broke](https://user-images.githubusercontent.com/45996677/76566707-9d55ff00-64ad-11ea-8505-c697be7901bf.png)

**Comment by Izheil** [comment] 2020-03-12 23:30
![Sin título](https://user-images.githubusercontent.com/33794458/76575874-d055be00-64c0-11ea-90d0-545fe94dba5a.png)
I still can't reproduce the issues you are experiencing.
Tried on Linux as well, with the same results.

Try to clean the startup cache (about:profiles > local directory > delete everything inside the startupcache folder), and try with an unmodified userChrome.css file.

Alternatively, you can try debugging which part is giving you issues deleting parts of userChrome from the end (delete the bottom 3 or 4 rules each time before restarting firefox) to the beggining to test which one is the rule that is giving you problems.

**Comment by Izheil** [comment] 2020-04-03 08:56
@Captaindl and @DasRentier, any news on if you got it fixed, or should I close this?

**Closed** 2020-04-08 04:26 UTC
Labels: Bug, Needs more Info
