### ISSUE TITLE
[BUG] Text box, hard to see history

### ISSUE THREAD

**Issue by forplan0** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#71] opened 2020-06-12 16:17 UTC
Hello,  
Just me or is this like normal?

I have hard to see past (history) text in text box (in attachment).

I think it will be better text with other color, white or blue or...

https://i.ibb.co/FzjP4qm/asd.jpg

**Comment by Izheil** [comment] 2020-06-12 17:08
What page does this happen on?

**Comment by forplan0** [comment] 2020-06-12 19:56
Previous site been: sammobile.com

But this is not site related, because i have same problem on any site that use default text box

Also other text (photo) is in same color, hard to read.

Maybe is on my side? What should i look? 

I have clean firefox from last week, i just put your theme over it...

https://i.ibb.co/9pBFBPQ/asdasd.jpg

**Comment by Izheil** [comment] 2020-06-13 04:04
![Sin título](https://user-images.githubusercontent.com/33794458/84559460-1843e580-ad3b-11ea-9952-48260e4201a0.png)
![Sin título2](https://user-images.githubusercontent.com/33794458/84559477-3a3d6800-ad3b-11ea-907a-ed7b493625b8.png)

Seeing that the sammobile autocomplete is dark for you when it shouldn't it seems like something external is affecting the autocomplete context menus...

Does it happen on right click menus?

In either case, it seems to be related to either an operative system theme (if you installed a custom theme in windows, not the default dark or light ones, or if you installed some theme in linux that leaks into pages forms), or a theming addon.

Try Firefox in safe mode or in a new profile and see if the issue persists.

**Comment by forplan0** [comment] 2020-06-14 14:50
Thank you for trying resolve my problem...

It's something on my side. Now i thinking windows problem...

I remove firefox, clean install and your theme and is same...

In windows i just use black theme nothing other custom.. But i didn't update in more then half year because license problem... I don't have problem with anything other in windows...

I will try next week on my work PC to install your theme and i will see...

**Comment by forplan0** [comment] 2020-06-16 13:03
Today at work i install some virtual machine (new window 10, latest...) and i just try install firefox and your theme.

I got same problem on same site sammobile.com:  https://i.ibb.co/vYQtL7j/test.png

I also try set light color of windows and i got this. Text in bookmarks toolbar is unreadable https://i.ibb.co/rbYxYbd/Zajeta-slika.png
If i set dark windows colors around bookmarks colors of fonts are ok

**Comment by Izheil** [comment] 2020-06-16 16:06
The theme doesn't seem to be getting fully registered (your url bar isn't even dark).
How did you install the theme?
Did you clone the repository:

![clone](https://user-images.githubusercontent.com/33794458/84798492-4fe0b500-affb-11ea-89c2-662dbd2cff5c.png)

...and then copied `userChrome.css` and `userContent.css` to your chrome profile folder (as it appears on `about:support`)?

![aboutsupport](https://user-images.githubusercontent.com/33794458/84798997-ead98f00-affb-11ea-87c9-1f5870a848ab.png)

Sometimes people have tried to copy the files directly and forgot to click the "raw" option when copying it to their userchrome... which causes those kind of issues.

**Comment by Izheil** [comment] 2020-07-05 15:10
To anyone stumbling upon this bug in the future, if you still have this bug (which I can only assume is somehow related to some Windows color registry getting changed for some reason, since this theme doesn't have code that affects autocomplete menus), you should still be able to change the autocomplete menus adding this to your `userChrome.css`:

``` CSS
#PopupAutoComplete .autocomplete-richlistbox {
	background-color: #fff !important;
	color: #000 !important;
}
```

It's not a perfect solution, since it will change the autocomplete menu colors to white background and black text color (just change the `background-color` to `#333` and `color` to `#ccc` if you are using a dark theme for all sites on stylus) for every site, ignoring per-site themes.

**Comment by Izheil** [comment] 2020-07-05 17:26
So I found there was some missing pseudoselector in the code that was only suposed to affect the login autocomplete, which was the source of the issue.

I had it in my local copy, but I must have copied it wrong when uploading it, which was why I couldn't reproduce it.

It should be fixed now, and the autocomplete popups will get themed to remain consistent with the rest of the popup elements like select boxes.

**Closed** 2020-07-05 17:26 UTC
Labels: Bug
