### ISSUE TITLE
Fatal error in Patcher 

### ISSUE THREAD

**Issue by Traveler4** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#59] opened 2020-04-30 15:15 UTC
**Describe the bug**
When the patcher is executed, the following window appears:
![image](https://user-images.githubusercontent.com/52359342/80726878-49f34b00-8b05-11ea-8d73-56934e39f838.png)

**To Reproduce**
- Download the [Patcher](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases/download/FF75/Multirow-Patcher-Quantum-Nox-Installer-Win-1.4.5.exe) 
- Execute it by doubleclick

**Expected behavior**
- Not a fatal error

**Screenshots**
- see above

**Environment**
 - OS: Win10 Version 1909, Build 18363.778
 - Version: the patcher was placed in the root directory of an installation of [FF75.0 Portable](https://portableapps.com/de/apps/internet/firefox_portable)

**Additional information**
- none

**Comment by Izheil** [comment] 2020-04-30 22:53
I'm executing it from the same enviroment and the program window appears. Make sure that your antivirus isn't silently blocking it, and try running it as administrator.

**Comment by Traveler4** [comment] 2020-05-01 08:41
I retried running it as an Administrator and with my Antivirus SW Avast being disabled (and the other three possible combinations), but with the same result.
[This page](https://docs.python-guide.org/shipping/freezing/) compares some freezing tools and notes that most of them require "*Microsoft Visual C++ to be installed on the target machine*". I have slight doubts about the statement, but yes: MS Vis C++ is not installed on my machine. What tool/utility did you use to create the exe?
[Googling](https://www.google.com/search?q=fatal+error+failed+to+execute+script) found the following, which might possibly help: [stackoverflow](https://stackoverflow.com/questions/44641941/pyinstaller-fatal-error-failed-to-execute-script-when-using-multiprocessin), [github](https://github.com/pyinstaller/pyinstaller/issues/3446).

**Comment by Izheil** [comment] 2020-05-01 10:11
I used pyinstaller, which already bundles all required DLL files to the executable (as stated in the link you passed), so that shouldn't be the issue.
> Only PyInstaller makes a self-executable exe that bundles the appropriate DLL when passing --onefile to Configure.py.

The other links you provided don't seem to relate to any of the functions used in the patcher, no multiprocess, nor missing dependencies.
Try uncompressing this file and run it. A console should appear when you start it showing some error.
[Quantum-Nox-Installer_with_console.zip](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/files/4563384/Quantum-Nox-Installer_with_console.zip)

Paste the error here to see if we can debug it.

**Comment by Traveler4** [comment] 2020-05-01 12:30
Thankyou for looking into it. Here is the console output:
![grafik](https://user-images.githubusercontent.com/52359342/80799497-44e6d800-8ba7-11ea-8323-8943c4cd12d0.png)

The output is correct, 
`c:\users\Admin\AppData\Roaming\Mozilla\Firefox\Profiles\` does not exist. Instead, the data is in 
`c:\users\User1\AppData\Roaming\Mozilla\Firefox\Profiles\`.

I assume that the following is happening: When the Patcher is executed, it asks for Admin privileges. When these are granted, the program executes in the context of the Admin, therefore assuming the `AppData\Roaming\Mozilla`-data to be found under `c:\users\Admin\`, whereas in fact, they are under `c:\users\User1\`.

I was not able to run the Patcher (neither the downloaded version nor the console-version) in the context of `User1`. The exe's are shown with the blue/yellow shield icon overlaid, but `Execute as Administrator` is not ticked:
![grafik](https://user-images.githubusercontent.com/52359342/80805012-22f55180-8bb7-11ea-87e3-0df487454b3d.png)

**Comment by Traveler4** [comment] 2020-05-01 12:40
PS: I just tried
`runas /user:User1 Quantum-Nox-Installer_Console_ON.exe`
but that yields
`Error 740: The requested operation requires elevation`

**Comment by Izheil** [comment] 2020-05-01 13:16
The program will request admin from the python file, which is why the "execute as administrator" isn't ticked, but requires administrator privileges either way.

The way I get the profile path is checking for the %appdata% enviroment variable (which points to the roaming folder), but in your case it seems to direct to the wrong place?

Open the console (search cmd on start menu and execute it, or `windows key + r`, and then type `cmd` in the dialog window), and then type `echo %appdata%`.
If everything is working right you should see `C:\users\User1\AppData\Roaming` instead of the Admin alternative.

**Comment by Traveler4** [comment] 2020-05-01 13:28
If I do `echo %appdata%`
* on a console in the context of `User1`, I get `C:\Users\User1\AppData\Roaming`
* on a console in the context of `Admin`, I get `C:\Users\Admin\AppData\Roaming`

**Comment by Izheil** [comment] 2020-05-01 14:19
Alright, test this file, and tell me what values it gives you in the context of Admin:

[test.zip](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/files/4564661/test.zip)

**Comment by Traveler4** [comment] 2020-05-01 14:26
![grafik](https://user-images.githubusercontent.com/52359342/80812522-715f1c00-8bc8-11ea-931c-b442584175b4.png)

**Comment by Izheil** [comment] 2020-05-01 16:52
Well, there doesn't seem to be any way to get the underlying user while running the process as admin, so I guess the only way to fix this would be to call a subprocess to do the admin-related things... but I'm kind of tired right now, so I'll see what I can do tomorrow.

**Comment by Traveler4** [comment] 2020-05-01 18:38
Thanks for your efforts!
Not elegant, but another idea: require the user to copy the tool into a certain folder (e.g. `C:\Users\User1\AppData\Roaming\Mozilla\Firefox\`) and to run it from there. Then the tool can access the required path relative to its own path.

**Comment by Izheil** [comment] 2020-05-02 06:11
The problem is that pyinstaller bundles the required python dependencies into a temporary folder, so even if you run the .exe from a given path, you won't be able to obtain that location, since the current working directory will point to the location where the underlaying `.py` is being executed from.

In either case, I think I managed to fix it!
The patcher executable will now bundle a new file, ([FindNonRootId.bat](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/master/Installers/FindNonRootID.bat)) which will just temporally copy the user `%appdata%` path location to `C:\Users\Public\QNUsername.txt` when you launch the patcher before starting administrator mode.

This txt file will get deleted it as soon as it fetches the non-admin username.

Try fetching the [new release](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases) and see if that works for you.

**Comment by Traveler4** [comment] 2020-05-02 12:54
Thanks for the explanation.

Wow, great - it works! That's cool!

Two remarks to finish:
* The sourcecode uses `C:\Users\Public` hardcoded. I think, it would be safer to use the environment variable `%public%` instead.
* The date on the latest entry in the [Patch notes](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases) is incorrect.

**Comment by Izheil** [comment] 2020-05-02 23:46
You are right. Sometimes these things escape our mind while testing!
Thanks for noting those.
I'll fix those and close this.

**Closed** 2020-05-03 00:05 UTC
Labels: Bug
