### ISSUE TITLE
Closed tabs reappearing when using multirow with Tab Session Manager

### ISSUE THREAD

**Issue by PaddlesAU** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#46] opened 2019-03-07 14:27 UTC
I've found that if I have both the multirow chrome changes and the Tab Session Manager addon active at the same time, then when I close Firefox and reopen it, the last three closed tabs are reopened. If only one or the other is present, then this doesn't happen. Logged both here and with TSM at https://github.com/sienori/Tab-Session-Manager/issues/290#issuecomment-469673328

**Comment by Izheil** [comment] 2019-03-08 01:02
Which multirow version are you using, scrollbars, or infinite rows (the default)?

Also, which version are you using of Firefox, stable (65.0.2), nightly, beta, or ESR?

and lastly... do you have "restore previous session" ticked on in <code>about:preferences</code> (as in... does it restore 3 tabs even when you <b>don't want</b> to restore any session from the start, or it only restores 3 tabs of your previous session that you <b>did want</b> to restore)?

I've been using TSM with scrollbars multirow and I've never experienced this issue.

**Comment by PaddlesAU** [comment] 2019-03-09 12:01
You've understood the bug report correctly.

I tried applying the fix (also updated userChrome.css because I hadn't applied the last few changes), it didn't work. I also saw a new problem - if I closed tabs at the end of the set of tabs, and then opened some new tabs, the new tabs were appearing after a gap (i.e. the last row of tabs now looks like five tabs, then three tabs' width of space, and then the newly opened tabs) - noting that in the past I've overridden the tab `min-width` and `max-width` settings to both be 100px. The removed tabs also reappear when I restart Firefox.

The fix that seemed to work was to change tab flex-grow to 0 i.e.
```
    .tabbrowser-tab:not([pinned]) {
        flex-grow: 0;
        min-width:100px !important;
    }
```

I don't know why this should make a difference, but it seemed to fix it. Notes:
* In all my tests, I left `#alltabs-button, .tabbrowser-tab:not([fadein]` out as per your last change.
* I also had to make sure I'd checked the tab listing in the last-saved session for Tab Session Manager and manually remove the most recently deleted tabs if they were still appearing. Between these two actions, that seems to have worked.
* It also worked with just `flex-grow:0` (i.e. not setting `min-width`) - though that gives a smaller minimum width than I wanted.
* I did test some other combinations to see if they worked, noting that not all users would like a fixed tab width. `flex-grow: 1` still seemed to cause problems, but I can't see why.

**Comment by Izheil** [comment] 2019-03-09 14:18
Hmm... for me, deleting <code>.tabbrowser-tab:not([fadein])</code> was enough, (we didn't need to delete <code>#alltabs-button</code>, which is why I guess the gap appeared for you, although for some reason it didn't appear to me). 

Even with flex-grow: 1 it still works for me after deleting the previously mentioned selector, so I'm not sure what could be causing this issue.

Which Firefox version and OS are you testing this on?

In either case, it seems like it's most probably a Firefox issue, since I doubt that TSM checks for active tabs through checking the width.

Since the issue only seems to appear when tampering with the tabs flexible size (the selector we deleted removed the resize animation on tab opening and closing), I assume that it's some issue with Firefox not registering the event triggers right when an element resizes.

**Comment by Lim4multirowtab** [comment] 2019-03-13 05:28
Hi Izheil,

As I had the same issue with closed tabs coming back each time a restart FF, I updated with your last MultiRowTabLiteforFx.uc.js

But now, when I reopen FF and close the tabs that should not be there again, they disappear, but the space where they were remains. There is just an empty space between the other tabs.
And moreover, they reappear anyway after reopening.

Also, another subject, I have to edit the file as you kindly advised me before because, you added a min-width and then the max-width make each tab bigger in height...
```
.tabbrowser-tab:not([pinned]) {
        flex-grow:1;
    	max-width: var(--tab-min-width) !important}
```

**Comment by Izheil** [comment] 2019-03-13 06:23
I removed the last update from multirow now (since it doesn't seem to fix the issue anyway), so the empty space shouldn't happen anymore. 

As for why Tab Session Manager saves those last closed tabs while the default FF session one doesn't is still a mystery.

I can't do much more on my side about the issue, since the thing that causes it seems to be related to flexboxes or tab resizing animations (which are required for multirow to work as intended), but I don't see any reason for those to interact with TSM active tab logging for sessions apart from some posible Firefox bug.

**Comment by Lim4multirowtab** [comment] 2019-03-13 06:29
Then I believe the best is to stick with your version dated 01/02/2019 and close old tabs.
At least, there won't be the empty spaces.

**Comment by PaddlesAU** [comment] 2019-03-13 11:44
I've pulled the latest versions and tried running some more tests.
* All works fine when no `max-width` specified.
* Problem reoccurs when `max-width` is specified.
* Changing `flex-grow` to 0 no longer fixes problem.
* Adding `.tabbrowser-tabs[collapsed]` to the selector at the end of the CSS= definition doesn't fix the problem.

Running 65.0.2 64-bit stable (not nightly, beta etc.) on Win10 64-bit:
* Using a separate test profile with only Tab Session Manager, Undo Close Tab, Simple Close Tab, and CSS changes (MultiRowTab-scrollable.uc.js version) and no manual changes to about:config 
* "Restore previous session" is selected in Tab Session Manager, not selected in Firefox general options (although I notice the problem happens if i switch round the other way too.)
* TSM has lazy loading on.

As another test, I tried removing Tab Session Manager, installing a different session management extension (Session Boss), and removing Undo Close Tab just in case.  The problem continued to happen.

**Comment by Izheil** [comment] 2019-03-13 19:50
So the issue only happens when having <code>max-width</code> specified?

...but I didn't have any max-width or min-width specified by default before and it still happened.

Even now we have a <code>min-width</code> not a <code>max-width</code>. 

You did mention that you specified both to be 100px before, but only <code>min-width</code> should be needed when having <code>flex-grow</code>.

If you wanted to set the starting size of the tabs, you'd have to use <code>flex-basis</code> instead of <code>max-width</code>.

I haven't experienced the issue since removing the <code>.tabbrowser-tab:not([fadein])</code> that we mentioned at the start, and I'm testing from Win10 64bits as well with your same settings (Undo close tab included), so Im not sure why is it still happening for you.

I assume it must be because of some local changes like the <code>max-width</code> you mentioned, so try replacing the file from the repository directly and see if it still happens.

**Comment by PaddlesAU** [comment] 2019-03-14 12:28
Ahh, that's the danger of (me) knowing a little CSS, but not enough (and not RTFM). When I used
```
.tabbrowser-tab:not([pinned]) {
        flex: 0 0 100px}
```
then it worked as desired - all tabs the same width, no gaps appearing, and deleted tabs not reappearing. (For those playing at home, `flex: 0 0 100px` is equivalent to `flex-grow: 0; flex-shrink:0; flex-basis: 100px` which means set initial size to 100 px, and don't grow or shrink - but using the expected attributes for a flex-box.)

So thanks for pointing me in the right direction!

Would `flex: 1 0 100px` make more sense as the standard code, rather than using min-width?

**Comment by Izheil** [comment] 2019-03-14 22:47
Min-width is only used to set the size up to which it can shrink (so if you have a row full of tabs and you set a min-width of 100px, the tabs which should start as something around 200px will shrink up to that size when the row is full of tabs).

Flex-basis sets the initial max size of the tabs (the size that would appear when the row isn't full, so for example when there is only 1 tab in a row). The reason for me not specifying this is that I prefer the default initial size of tabs (also to avoid changing what Firefox does by default too much), although I could add a commented flex-basis rule for those that want smaller initial size or fixed tab size with a comment of what's it for.

If we don't set min-width, tabs will shrink down to the size that you have set in<code>about:config</code> on the <code>browser.tabs.tabMinWidth</code> property (which is 76px by default).
The reason I had deleted min-width before was because of this setting already existing on <code>about:config</code>, but I guess having all settings in the same file would make more sense.

If you don't need min-width you can delete it altogether, and the <code>about:config</code> min-with property (which is 76px by default) will apply (although to me it's a bit small, which is why I set it as 100px).

So... yes, the short <code>flex: 1 0 100px</code> would make more sense if we wanted to set the initial size of tabs as well, but not so much if we only want to specify the minium size which it could shrink to. 

Either way, thanks for taking the time to test it throughfully to the end!

**Closed** 2019-03-18 00:23 UTC

**Comment by Lim4multirowtab** [comment] 2019-03-19 14:30
> 
> 
> Hi Izheil,
> 
> As I had the same issue with closed tabs coming back each time a restart FF, I updated with your last MultiRowTabLiteforFx.uc.js
> 
> But now, when I reopen FF and close the tabs that should not be there again, they disappear, but the space where they were remains. There is just an empty space between the other tabs.
> And moreover, they reappear anyway after reopening.
> 
> ![Closed tabs empty spaces](https://user-images.githubusercontent.com/47348157/54256475-9d0ee500-4575-11e9-8ff9-bfa20a95e3ac.jpg)
> 
> Also, another subject, I have to edit the file as you kindly advised me before because, you added a min-width and then the max-width make each tab bigger in height...
> 
> ```
> .tabbrowser-tab:not([pinned]) {
>         flex-grow:1;
>     	max-width: var(--tab-min-width) !important}
> ```

Hi Izheil,
After updating to FF66 and change to MultiRowTabLiteforFxFF66.uc.js, I have the the same issue as explained with the screenshot attached. Closed tabs just leave a black space and the most right tab does not move to the left.

**Comment by Izheil** [comment] 2019-03-19 16:53
@Lim4multirowtab, For FF66 you had to use the <code>MultiRowTabLiteforFxFF66.uc.js</code> version.
Either way, I just renamed them now to reflect the recent update, so overwrite your old <code>MultiRowTabLiteforFx.uc.js</code> with the actual repository one (will be the updated version).

**Comment by Lim4multirowtab** [comment] 2019-03-19 17:44
I was already with `MultiRowTabLiteforFxFF66.uc.js` after updating to FF66 as said above, but even when overwriting with your latest `MultiRowTabLiteforFx.uc.js` (renamed for FF66 and above), I still have this ghost tab remaining after closing.
Wonder why...

**Comment by Izheil** [comment] 2019-03-19 19:06
Make sure that you don't have any custom code on <code>Userchrome.css</code>, and that you haven't added the max-width property on any of the tabs selectors on either the multirow files or userchrome.

**Comment by Lim4multirowtab** [comment] 2019-03-20 03:46
So I tried, but no  change :(

The only thing I change in `Userchrome.css` is the drop shadow for glow effect over the tabs site icon: I set it to 0 instead of 3px

So to summarize, the 2 issues I have so far are:
- the closed tabs that reappear when FF is closed and open again
- when a tab is closed, the space is not taken by the tab from its right (this the same for the + to create a new tab)

**Comment by Lim4multirowtab** [comment] 2019-03-20 05:03
Ok some improvement.

With 
` /* MULTIROW TABS CSS */
    .tabbrowser-tab:not([pinned]) {
        flex-grow:1;
	min-width: 70px;
    	max-width: var(--tab-min-width) !important}`

It seems that there is no more come back of previously closed tabs and the tabs closed let the right ones to move to the left, EXCEPT, for the + at the end of the last row, which stays on its previous position and does not close the gap with the last opened tab.

![2019-03-20_090308](https://user-images.githubusercontent.com/47348157/54660236-069b7000-4aef-11e9-8221-ee42667357f1.jpg)

**Comment by Izheil** [comment] 2019-03-20 05:30
> 
> 
> Make sure that you don't have any custom code on `Userchrome.css` that could have affected tabs (try with a fresh install of userchrome to check), <b>and that you haven't added the max-width property on any of the tabs selectors on either the multirow files or userchrome.</b>

We already debugged this issue, and the culprit was <code>max-width</code>. If you aren't using Tab Session Manager, create a new issue, since it's not related to the one that we were speaking here.

As for the gaps, there is nothing in the code that could cause that (I have tested multirow on FF66, FF68, Win10, and Win7, and this issue never happened), so either you have added something else to the default code of any of the files, or some extension is messing it up.

Backup <code>all files</code> you have on your chrome folder, and <code>test it with only untouched versions</code> of the repository, because otherwise I can't know for sure that the issue isn't caused by some change you applied on any of the files.

**Comment by Lim4multirowtab** [comment] 2019-03-20 06:04
Yes I know, it's not easy for you to understand what is going on, especially with guys like me that are not coders and try to change things step by step.

So I have moved on a little bit.
The gap issue is resolved by just keeping:
`/* MULTIROW TABS CSS */
    .tabbrowser-tab:not([pinned]) {
    flex-grow:1;
    min-width: 70px !important}`

The only thing is that the last row tabs are huge, 6 or 8 tabs fill the all row, meaning each one can be 200px wide, or more maybe.
It is like the + had to be at the end of the row. Because when opening FF, or sometimes after closing a tab, the bottom tabs have the same size as others, but for half a second only.

So at least, the process of closing tabs seem to work okay, only the looking of the last row is weird.
Can we do something about it?

And for the height of tabs, I did some search and a believe I have to add some code as I haven't found where I could adjust it...

**Comment by PaddlesAU** [comment] 2019-03-20 10:22
I didn't like the oversized tabs either, which is why I've gone for
```
    .tabbrowser-tab:not([pinned]) {
        /* flex-grow:1;       /* replaced with next line for fixed size tabs */
        flex: 0 0 100px;
        min-width: 100px important!}
```
(Obviously you can change both values to 70px or whatever your preferred width is.)

**Comment by Lim4multirowtab** [comment] 2019-03-20 17:35
Perfect PaddlesAU, it works exactly the way I was expecting, thank you very much!

Do you know also how to reduce the height of all tabs? I used to be able to do it, but I don't remember how... :(

I wish I would understand a little about coding...

**Comment by Izheil** [comment] 2019-03-20 20:09
Now, said that, while both the original issue and the issue you were commenting were related to closed tabs at some extent, what you are asking now has absolutelly nothing to do with the Tab Mix Plus issue anymore. 

If you have a different issue than the title of the issue, please, open a new issue.
That way people with the same problem as you can also find a solution, and people that aren't interested in the other issues you have won't need to skim through the whole thread to see if there was something else to add to the original one.

I'll try to answer to this last one here, but if you keep having other issues with the tabs, open a new issue.

To change the height of tabs should be obtainable adding <code>--tab-min-height</code> to the :root selector:

<pre>
root { 
  --max-tab-rows: 3; 
  --tab-min-height: 20px !important}
</pre>

This will, although, not change the height of the close/resize/minimize buttons (which will push the height of the tab bar up to their height), so the tabs might look like they are floating at the top of the tabs bar when having less than your max number of set rows (3 by default).

If you wanted the whole tab toolbox to be 20px height, you'd have to also add this other selector rule below the root one: 

<pre>#TabsToolbar * {max-height: var(tab-min-height) !important}</pre>

The problem with this last one is that any buttons on the tab bar (including the open new tab and min/resize buttons) will look squished.
