### ISSUE TITLE
Multirow Doesnt´work with official Version FF 74 + Installer 1.41

### ISSUE THREAD

**Issue by Thomas000101** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#53] opened 2020-03-11 15:42 UTC
The official Firefox 74 version is currently installed. The 1.41 version installed and multirow does not work with it.
Tabs below works fine ...

**Comment by Izheil** [comment] 2020-03-11 21:54
If you are using Linux, the issue should be fixed now.
If you are using Windows... the installer seems to work fine there, so make sure the <code>MultiRowTab-scrollable.uc.js</code> file (or any other alternative you chose) was copied to your chrome folder. If it is, try to replace it <a href="https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/Multirow%20tabs">with the one from the repo</a> and see if the issue persists.

**Comment by Thomas000101** [comment] 2020-03-11 22:44
Iam with Windows 10 - Firefox 74
and Windows 7 on VM - Firefox 74

I have done what you said. ---> run 1.41 installer and replaced it with my chsoen file you suggest in the Link and put it in the chrome directory.
Can`t get it to work till now...
It shows only 1 row and a drop down arrow on the right... 
Only Tabs below work for me

**Comment by Izheil** [comment] 2020-03-11 23:22
I'm testing on W10 and it works as intended. 
The extra rows only appear as you open more tabs (usually 23 or more, depending on the screen resolution), which is when they are actually needed, so the screenshow is not telling me anything.

Use Ctrl+t to open 30 new tabs and see if it works.

**Comment by Thomas000101** [comment] 2020-03-11 23:30
Doesnt work...
![123](https://user-images.githubusercontent.com/62068696/76473404-a6d15f80-63f8-11ea-9b0f-b151df28ccc8.PNG)

**Comment by Thomas000101** [comment] 2020-03-11 23:44
I have installed the new 1.42 now... And it works! :)

**Comment by Izheil** [comment] 2020-03-11 23:48
![Sin título](https://user-images.githubusercontent.com/33794458/76474011-8acebd80-63fa-11ea-81eb-7c99e51083c7.png)
<s>I still can't seem to replicate on w10 nor on w7.</s>
I guess I copied something wrong on 1.41 builder if it works on 1.42, but if it's working now, it's all good!

**Closed** 2020-03-11 23:48 UTC
