### ISSUE TITLE
[REQUEST] Command line support

### ISSUE THREAD

**Issue by pauby** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#62] opened 2020-05-07 08:51 UTC
**Describe the solution you'd like**
I'd like to be able to run the Installer EXE from the command line and have it patch Firefox with the options I want.

I can see there is a `/Q` and `/C' parameter that can be passed to the EXE but, as far as I can see, they are not documented.

**Comment by Izheil** [comment] 2020-05-08 01:00
> I can see there is a `/Q` and `/C` parameter that can be passed to the EXE but, as far as I can see, they are not documented.

That's because it was never suposed to be a CLI, otherwise a `.bat` and `.sh` would probably have been much better alternatives (specially when antivirus softwares don't seem to like executables made with pyinstaller, but were okay with `.bat` files doing similar things before).

Anyway, when you say that you want to be able to run the installer from the command line, I assume you mean with a set of parameters, like how ffmpeg or other similar CLI programs work?

So some random command would look something like...
``` 
Patcher.exe -r stable -p * -f MR[300];TB;FT
```

**Comment by pauby** [comment] 2020-05-10 12:57
> Anyway, when you say that you want to be able to run the installer from the command line, I assume you mean with a set of parameters, like how ffmpeg or other similar CLI programs work?

Yes. So I could for example have the `/profile` parameter to give the path to the Firefox profile, `/multirowtabs 3` parameter to set the rows to 3 etc. The example you gave would work, I think it is more difficult to read. But I'd rather have command line parameters that are difficult to read than none at all so whatever is easiest to code.

The reason I am looking for this is primarily to create a [Chocolatey](https://chocolatey.org/packages) package to distribute it.

**Comment by Izheil** [comment] 2020-05-10 23:41
Will see what I can do.
I'll try to give both shorthand and long commands like in your examples where possible.

**Comment by pauby** [comment] 2020-05-11 11:22
Awesome. Thank you!

**Comment by Izheil** [comment] 2020-05-16 15:22
The refactoring was finished, and command line support was added on version 1.6.0!
You can check the [documentation in the wiki](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/wiki/Installer-console-commands).

You can run the commands with the exe, but you will only be able to see text output in the python version when running it under an administrator privileged console.

**Comment by pauby** [comment] 2020-06-03 09:53
Apologies for not coming back to you sooner on this. Been incredibly busy. I haven't yet tried this but will roll it up into a Chocolatey package soon.

Many MANY thanks for doing this!

**Comment by Izheil** [comment] 2020-06-03 10:21
No problem!

I usually close issues that are not reproducible or that I got working on my end after 2 weeks of inactivity (since sometimes people report some issue but then never come back to give more feedback for debugging), but I understand that sometimes people are just busy (in which case at least they will get notified that it got closed!).

I'll reopen it until you try it to see if there is any issue by now.

**Comment by pauby** [comment] 2020-06-03 10:51
I get it. I'll let you know if I come across any issues, or not. That way this issue doesn't hang around open forever.

**Comment by pauby** [comment] 2021-09-05 15:43
It's been a _very_ long time coming, but I've created and uploaded the Chocolatey package promised. See [the package page](https://community.chocolatey.org/packages/firefox-quantum-nox).

**Comment by Izheil** [comment] 2021-09-06 05:15
Looks good to me, although I'm not sure it will pass the virus tests, considering Windows Defender sometimes flags the patcher along with other minor brands AV's nowadays.

We'll have to wait and see.

**Comment by pauby** [comment] 2021-09-07 09:10
Package is now approved and [virus detections](https://community.chocolatey.org/packages/firefox-quantum-nox/1.7.21#virus) are within the levels we'd consider for false positives!

One thing I'd mention is that to automatically update the package the [code looks for a regex match](https://github.com/pauby/ChocoPackages/blob/master/automatic/firefox-quantum-nox/update.ps1#L21) on the releases page. If the naming of this changes, the automatic update will not be able to detect it.

**Comment by Izheil** [comment] 2021-09-07 14:51
Good to know. Since I always use the same naming convention there shouldn't be any issue.

I just noticed this but the description on the package mentions that the installer adds the dark theme and scrollbar customization, which isn't exactly right, since the installer is just for multirow, tabs below, megabar enlarge disabling, and focus tab on hover.

Apart from that I'll add a reference to it to the installation page with the due credit.

**Comment by pauby** [comment] 2021-09-07 17:28
> I just noticed this but the description on the package mentions that the installer adds the dark theme and scrollbar customization, which isn't exactly right, since the installer is just for multirow, tabs below, megabar enlarge disabling, and focus tab on hover.

I took the description from the [README.md](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme).

> Apart from that I'll add a reference to it to the installation page with the due credit.

Thanks.

**Comment by Izheil** [comment] 2021-09-10 08:12
Sure, I think this should work:

```
This package allows you patch Firefox to enable the use of external Javascript files to extend it's functionability. Some of the features you can install are multirow tabs, tabs below, or focus tab on hover.
```

Once that's done I think we could close this issue (at least until the next major version of the installer is released, which will change how it's installed).

**Comment by pauby** [comment] 2021-09-11 17:29
Update the [description](https://github.com/pauby/ChocoPackages/commit/7949af9ff8d6695152c1c1d19a76f462dac310ab).

The package at the moment simply renames the EXE to something shorter to type on the command line and then drops it on the file system (and optionally runs it with parameters passed in). If you rename the installer the package automation will have to be updated so please let me know.

**Comment by Izheil** [comment] 2021-09-12 14:44
Alright, I'll reopen this when a new major version is released, since I'm not planning to change the releases version until then.

All seems good with that package by now, so I'll close this.

Once again, thank you for taking the time for the package.

**Closed by Izheil** 2021-09-12 14:44 UTC
Labels: Enhancement, Installer
